# Set variables once
variables:
  solutionType: DotNetCore # angularDotNetCore, dotNetCore, angular
  apiDirectory: 'BookingsAPI/Bookings.API'
  sonarCloudExtraProperties: |
    sonar.cs.opencover.reportsPaths=$(Common.TestResultsDirectory)\Coverage\coverage.opencover.xml
    sonar.coverage.exclusions=Bookings.API/Program.cs,Bookings.API/Startup.cs,Bookings.API/Extensions/**,Bookings.API/Swagger/**,Bookings.API/ConfigureServicesExtensions.cs,Testing.Common/**,Bookings.Common/**,**/Bookings.DAL/Mappings/**,Bookings.DAL/SeedData/**,Bookings.DAL/BookingsDbContext.cs,Bookings.DAL/**/DesignTimeHearingsContextFactory.cs,**/Bookings.DAL/Migrations/**,Bookings.Domain/Ddd/**,Bookings.DAL/Commands/Core/**,Bookings.DAL/Queries/Core/**,**/Testing.Common/**
    sonar.cpd.exclusions="**/Program.cs,**/Startup.cs,Bookings.DAL/Mappings/**,Migrations/**,SeedData/**,DesignTimeHearingsContextFactory.cs,Ddd/**,Testing.Common/**,Bookings.API/ConfigureServicesExtensions.cs,Bookings.API/Extensions/**,Bookings.API/Swagger/**,Bookings.Common/**"
  coverletCoverageExclusions: '[*]Bookings.Common.*,[*]Testing.Common.*,[Bookings.DAL]Bookings.DAL.BookingsDbContext,[*]Bookings.DAL.Mappings,[*]Bookings.DAL.Migrations,[*]Bookings.DAL.SeedData.*,[*]Bookings.DAL.Exceptions.*,[*]Bookings.DAL.Mappings.*,[*]Bookings.DAL.Migrations.*,[*]Bookings.DAL.Commands.Core.*,[*]Bookings.DAL.Queries.Core.*,[*]Bookings.Domain.Ddd.*,[Bookings.DAL]Bookings.DAL.DesignTimeHearingsContextFactory,[Bookings.API]Bookings.API.ConfigureServicesExtensions,[*]Bookings.API.Extensions.*,[*]Bookings.API.Swagger.*,[Bookings.API]Bookings.API.Program,[Bookings.API]Bookings.API.Startup'
  integrationTestsAppSettingsTransform: '
    "AzureAd/TenantId":"$(tenantid)",
    "AzureAd/VhBookingsApiResourceId":"$(vh-bookings-api-identifieruris)",
    "Testing/TestClientId":"$(vh-admin-web-appid)",
    "Testing/TestClientSecret":"$(vh-admin-web-key)"
    '
  dalWorkingDirectory: 'BookingsAPI/Bookings.DAL'
  keyVaultName: vhcoreinfrahtdev # Used to get secrets for integration tests
  secretsFilter: 'vh-admin-web-appid,vh-admin-web-key,tenantid,vh-bookings-api-identifieruris' # filters out secrets returned from key vault
  imageName: 'vhinfrastructure.azurecr.io/vh-docker:$(Build.BuildId)'
  azureSubscriptionEndpoint: 'Reform-CFT-VH-Dev'
  azureContainerRegistry: 'vhinfrastructure.azurecr.io'
  helmVersion: '2.12.3'
  runtimeIdentifier: 'ubuntu.16.04-x64'


# GitHub Repo that conatins build templates. Reference https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=vsts#using-other-repositories
resources:
  repositories:
  - repository: azureDevOpsTemplates
    type: github
    name: hmcts/azure-devops-templates
    ref: refs/heads/dotnet-core-build-rid # ref name to use, defaults to 'refs/heads/master'
    endpoint: 'GitHubDevOps'

stages:
- stage: Build
  jobs:
  - template: jobs/angularDotNetCore.yml@azureDevOpsTemplates # Template reference
    parameters:
        sonarCloudExtraProperties: $(sonarCloudExtraProperties)
        integrationTestsAppSettingsTransform: $(integrationTestsAppSettingsTransform)
        coverletCoverageExclusions: $(coverletCoverageExclusions)
        apiDirectory: $(apiDirectory)
        dalWorkingDirectory: $(dalWorkingDirectory)
        keyVaultName: $(keyVaultName)
        secretsFilter: $(secretsFilter)

  - job: BuildDotNetCoreProject
    displayName: .Net Core Project for $(runtimeIdentifier)
    pool: 'Azure-VSTS-VS2017'
    steps:
    # Runs common steps - gitVersion, Nuget  
    - template: templates/common/common.yml@azureDevOpsTemplates
    # build dotnet project
    - template: templates/dotnetRid/dotnetRidRestoreBuildPublish.yml@azureDevOpsTemplates # Template reference
      parameters:
          apiDirectory: $(apiDirectory)
          runtimeIdentifier: $(runtimeIdentifier)

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: dotentArtifacts

  - job:
    displayName: Docker Image
    dependsOn: BuildDotNetCoreProject
    pool:
      vmImage: ubuntu-16.04
    steps:

    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifacts'
      inputs:
        artifactName: 'dotentArtifacts'
        downloadPath: '$(Build.SourcesDirectory)/webapp'
        parallelizationLimit: 50
    
    - powershell: (Get-ChildItem -Recurse -Path "$(Build.SourcesDirectory)/webapp").FullName

    
    # - task: Docker@1
    #   displayName: Build image
    #   inputs:
    #     command: Build an image
    #     azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    #     azureContainerRegistry: $(azureContainerRegistry)
    #     dockerFile: Dockerfile
    #     imageName: $(Build.Repository.Name)

    - task: Docker@2
      displayName: Build
      inputs:
        containerRegistry: 'vh-acr-dev'
        repository: '$(Build.Repository.Name)'
        command: build
        Dockerfile: Dockerfile
        arguments: '--build-arg SourcePath="./webapp"'
        tags: |
          $(Build.BuildId)
          latest

    - task: Docker@2
      displayName: Push
      inputs:
        containerRegistry: 'vh-acr-dev'
        repository: '$(Build.Repository.Name)'
        Dockerfile: Dockerfile
        tags: |
         $(Build.BuildId)
         latest